{
 "title": "NGINX Telemetry",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nginx_instance",
    "label": "NGINX Instance",
    "query": "select distinct system_id from nms.metrics"
   }
  ]
 },
 "panels": [
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nginx_instance" },
  {
   "title": "HTTP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'nginx.http.conn.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641766753) AND timestamp <= toDateTime(1641768553)\n    and name like 'nginx.http.conn.%' and system_id = '9cbfd87a-4998-458b-9571-522fef84baee'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'nginx.http.request.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641071316) AND timestamp <= toDateTime(1641676116)\n    and name like 'nginx.http.request.%' and system_id = '9cbfd87a-4998-458b-9571-522fef84baee'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "NGINX Plus SSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'plus.ssl.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641070997) AND timestamp <= toDateTime(1641675797)\n    and name like 'plus.ssl.%' and system_id = '9cbfd87a-4998-458b-9571-522fef84baee'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "nginx_instance" },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.cpu.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 120) * 120) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641387717) AND timestamp <= toDateTime(1641673358)\n    and name like 'system.cpu.%' and system_id = '9cbfd87a-4998-458b-9571-522fef84baee'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.mem.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 120) * 120) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641387717) AND timestamp <= toDateTime(1641673358)\n    and name like 'system.mem.%' and system_id = '9cbfd87a-4998-458b-9571-522fef84baee'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "System I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.io.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641070850) AND timestamp <= toDateTime(1641675650)\n    and name like 'system.io.%' and system_id = '9cbfd87a-4998-458b-9571-522fef84baee'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.load.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 120) * 120) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641387717) AND timestamp <= toDateTime(1641673358)\n    and name like 'system.load.%' and system_id = '17ab67bb-fcbe-4cb0-adef-bc811033b6e8'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.disk.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 120) * 120) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641387717) AND timestamp <= toDateTime(1641673358)\n    and name like 'system.disk.%' and system_id = '17ab67bb-fcbe-4cb0-adef-bc811033b6e8'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "database": "nms",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    name,avg(value)\nFROM $table\n\nWHERE $timeFilter\n    and name like 'system.net.%' and system_id = '$nginx_instance'\nGROUP BY name,t\n\nORDER BY name,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 300) * 300) * 1000 as t,\n    name,avg(value)\nFROM nms.metrics\n\nWHERE timestamp >= toDateTime(1641070330) AND timestamp <= toDateTime(1641675130)\n    and name like 'system.net.%' and system_id = '17ab67bb-fcbe-4cb0-adef-bc811033b6e8'\nGROUP BY name,t\n\nORDER BY name,t",
     "round": "0s",
     "table": "metrics"
    }
   ]
  }
 ]
}